sudo: false
language: python

python:
  - "2.7"

before_install:
  - openssl aes-256-cbc -K $encrypted_7f8115fa5d54_key -iv $encrypted_7f8115fa5d54_iv -in ./travis/travis.rsa.enc -out ./travis/travis.rsa -d

install:
  - pip install -U pip setuptools
  - pip install git+https://github.com/antocuni/pytest-benchmark.git#egg=pytest-benchmark
#  - pip install pytest-benchmark

script:
  # - bash ./travis/clone-benchmarks-repo.sh
  # - py.test --benchmark-autosave
  # - bash ./travis/commit-results.sh
  - bash trytcpserver.sh
